version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  etherpad:
    image: etherpad/etherpad
    ports:
      - "9002:9001"