doodle:
  usepad: false
  padUrl: "http://etherpad:9002/"
  padApiKey: "fa8cce291d03acaf1dce7d137f73ce60aa2eeebdec77be42bcb8461d0e4278ea"
  organizermail: "olivier.barais@gmail.com"
  tmpfolder: "/tmp/excelFiles"
quarkus:
  datasource:
    db-kind: mysql
    username: root
    password: ""
    jdbc:
      url: jdbc:mysql://localhost:3307/tlc?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Paris
      driver: com.mysql.cj.jdbc.Driver
  hibernate-orm:
    database:
      generation: update
  mailer:
    from: test@quarkus.io
#    host: smtp.sendgrid.net
    host: localhost
    port: 2525
#    port: 465
#    ssl: true
#    username: ""
#    password: ""
    mock: false
  http:
    cors: true
    port: 9090
